name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Build Application
      run: npm run make

    - name: Package Application
      run: npm run package
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION }}
    
    - name: Upload .exe installer
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: './out/make/squirrel.windows/x64/warehouse_electron-${{ github.ref }} Setup.exe'
        asset_name: 'warehouse_electron-${{ github.ref }} Setup.exe'
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION }}
