name: Build and Release Electron App

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run make script
      run: npm run make

    - name: Run package script
      run: npm run package

#    - name: Build/release Electron app
#      uses: paneron/action-electron-builder@v1.8.1
#      with:
#        # GitHub token, automatically provided to the action
#        # (No need to define this secret in the repo settings)
#        github_token: ${{ secrets.GITHUB_TOKEN }}
